import { Geist, Geist_Mono } from "next/font/google";
import { ReportProvider } from "@/context/ReportContext";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BTA EAA Report",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReportProvider> {/* ✅ Wrap your entire app with the provider */}
          {children}
        </ReportProvider>
      </body>
    </html>
  );
}
